Add support for `MixedPart` and `RelatedPart`
stayallive/laravel-mail-css-inliner pull request #2
Opened 2022-03-21 14:26 UTC by Maxoulak

Add support for MixedPart (which can contains RelatedPart).

Useful when dealing with attachments & raw base64 images.

2022-03-23 13:44 UTC, Maxoulak commented
Hi @stayallive, could you please take a look at this PR ?

2022-03-23 13:46 UTC, stayallive commented
Hey @Maxoulak, I missed this for some reason... 

Can you please also provide some tests to prove that this code is working as intended for the features you implemented?

2022-03-23 13:52 UTC, Maxoulak commented
Of course, I'll come back to you in few days.

2022-03-24 09:09 UTC, RomulusED69 requested changes

2022-03-24 09:09 UTC, RomulusED69 commented on src/SymfonyMailerCssInliner.php
> +    }
```suggestion
    }

```

2022-03-24 09:23 UTC, Maxoulak commented
Hi @stayallive, I've just pushed new commits including tests and fixes.
IMO, all seems good working.

2022-03-24 10:08 UTC, merged

2022-03-24 10:08 UTC, stayallive commented
Hey @Maxoulak, this looks great, thanks 💪